{{- if eq (include "acm-member-portal.createDatabaseSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acm-member-portal.databaseSecretName" . }}
  labels:
    {{- include "acm-member-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
stringData:
  DATABASE_URL: {{ include "acm-member-portal.externalDatabaseUrl" . | quote }}
{{- end }}
